services:

  ollama:
    build:
      context: ./api
    container_name: rag_ollama_api
    env_file:
      - .env
    ports: 
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  python:
    build:
      context: ./web
    volumes:
      - ./web:/code
      - chroma_data:/code/chroma
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - PYTHONUNBUFFERED=1
      - CHROMA_PERSIST_DIR=/code/chroma
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  ollama:
    external: true
  chroma_data: